pipeline:
    name: TestPipeline
    identifier: TestPipeline
    allowStageExecutions: false
    projectIdentifier: GitSync
    orgIdentifier: RaviOrganisation
    tags: {}
    stages:
        - stage:
              name: Test
              identifier: Test
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: Service1
                      serviceDefinition:
                          type: Kubernetes
                          spec:
                              variables: []
                  infrastructure:
                      environmentRef: Development
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: account.AWS_Lab
                              namespace: test
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - step:
                                name: Rollout Deployment
                                identifier: rolloutDeployment
                                type: K8sRollingDeploy
                                timeout: 12m
                                spec:
                                    skipDryRun: false
                      rollbackSteps:
                          - step:
                                name: Rollback Rollout Deployment
                                identifier: rollbackRolloutDeployment
                                type: K8sRollingRollback
                                timeout: 12m
                                spec: {}
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
